### PR TITLE
Add a Progress Bar for the Stats in PokemonFullView Components

### LINKED ISSUE #1: Stylize 'PokemonFullView' component
The component named 'PokemonFullView' is a modal that display pokemon base-stats and upgraded stats. Stylize this component to look more aesthetically pleasing.  My suggestion is add a progress bar for the stats (ranging from 0 to 350). 

stylize

### PR DESCRIPTION
**Pull request by AbhishekJadhav2002**
Hello @nipeshkc7, sorry for the late reply. But I managed to work out on adding progress bar for showing stats in the range (0-350), and this is how it's looking now.

Screenshot
Please suggest changes, if any.
fixes #1

### CODE REVIEW

**Comment by AbhishekJadhav2002** [comment]
Also I wanted to ask that, is this project considered for Hacktoberfest'22 @nipeshkc7

**Comment by nipeshkc7** [comment]
> Also I wanted to ask that, is this project considered for Hacktoberfest'22 @nipeshkc7

Not a 100% sure for this year. Please check their guidelines: https://hacktoberfest.com/participation/

**Review by nipeshkc7 — APPROVED** [review]

**Comment by AbhishekJadhav2002** [comment]
> > Also I wanted to ask that, is this project considered for Hacktoberfest'22 @nipeshkc7
> 
> Not a 100% sure for this year. Please check their guidelines: https://hacktoberfest.com/participation/

I think for participations, you just have to add CONTRIBUTING.md file and hacktoberfest label in the repository.

**Comment by AbhishekJadhav2002** [comment]
@nipeshkc7 is this issue requires anything more ? Because, you haven't merged or closed it 😅
Or will you please add 'hacktoberfest-accepted' label, so that it might get considered for the contest.

**Pull request merged**
